#!/usr/bin/env bash
# changes your localhost ip and sets facebook.com ip
tmpfile=$(mktemp)

sed 's/127\.0\.0\.1/127.0.0.2/' /etc/hosts > "$tmpfile"
sed 's/^\(.*\)facebook\.com$/8.8.8.8 facebook.com/' "$tmpfile" > /etc/hosts

rm -f "$tmpfile"