#!/usr/bin/env bash
# changes your localhost ip and sets facebook.com ip
#localhost
tmpfile=$(mktemp)
sed 's/127\.0\.0\.1/127.0.0.2/' /etc/hosts > "$tmpfile"
cat "$tmpfile" > /etc/hosts
rm -f "$tmpfile"
#facebook
tmpfile=$(mktemp)
grep -v 'facebook\.com' /etc/hosts > "$tmpfile"
printf '8.8.8.8 facebook.com\n' >> "$tmpfile"
cat "$tmpfile" > /etc/hosts
rm -f "$tmpfile"